[package]
name = "Rusys"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["ZxFae33"]

[dependencies]
ratatui = { version = "0.30.0-alpha.0", features = ["all-widgets"] }
sysinfo = "0.33"
colored = "2.1.0"
crossterm = "0.28.1"
nix = { version = "0.29.0", features = ["net", "socket"] }
